In [58]:
import pandas as pd
import numpy as np

In [59]:
task_raw = pd.read_csv('.\\data\\raw\\data_exp_70408-v19_task_190122.csv')
demos_raw = pd.read_csv('.\\data\\raw\\data_exp_70408-v19_demo_190122.csv')

## Data needed

File 1, Checks; Index: part_id, Columns: total_time_ml, total_time_sec, rock_human_score, rock_god_score, math1_num_resp, math2_num_resp, math3_num_resp

File 2, Demos; Index: part_id, Columns: gender, age, politics, religiosity, academic, revenue

File 3, Data; Index: part_id, Columns: [all concepts total scores] [all comparisons]

File 4, Data; Index: concept, Columns: concept, Fill: score averaged over participants

In [60]:
# File 1



part_id_key = 'Participant Public ID'

In [198]:
# DEMOGRAPHICS LOGIC
demos_columns = ['Sex', 'Sex-quantised', 'Sex-text', 'age', 'academic', 'academic-quantised', 'revenue', 'revenue-quantised', 'politics', 'religiosity']
df_demos = pd.DataFrame(columns=demos_columns)

# Columns with relevant data
question_key = 'Question Key'
response_key = 'Response'

# Collect participant ID
part_ids_demo = demos_raw[part_id_key].dropna().unique()
part_ids_demo = task_raw[part_id_key].dropna().unique()


for ids in part_ids_demo:
    part_id = ids

    # Demos part
    demos_part = demos_raw[demos_raw[part_id_key] == part_id]
    # Clean dataframe of unused columns and rows
    demos_data = demos_part[[question_key, response_key]].drop(demos_part.tail(1).index, axis=0).dropna()
    # Collect columns
    new_cols = list(demos_data[question_key])

    # Adjust data format
    demos_idx = demos_data.drop(question_key, axis=1)
    demos_renamed = demos_idx.rename(columns={response_key:part_id})
    demos_T = demos_renamed.transpose()
    demos_T.columns = new_cols

    ##df_demos = demos_T

    df_demos = df_demos.append(demos_T)
    

df_demos

,Sex,Sex-quantised,Sex-text,age,academic,academic-quantised,revenue,revenue-quantised,politics,religiosity
5e8f4d8918ca6c2314765d92,Female,1,NaN,19,High school graduate,2,$50 000 - $69 999,5,6,24
614b53c4e3ff9739cc026895,Male,2,NaN,21,Bachelor's degree (3+),4,Less that $10 000,1,35,52
61133b44c0f877a21f27c3ee,Male,2,NaN,21,Some college but no degree,3,Less that $10 000,1,38,37
61088dc29d639b015d4cd918,Female,1,NaN,23,Some college but no degree,3,$30 000 - $49 999,4,28,26
6175b756491e339b289ca959,Male,2,NaN,33,Master's degree (5+),5,$30 000 - $49 999,4,53,2
60ad33772c5d282d6a2021e8,Female,1,NaN,26,Bachelor's degree (3+),4,$70 000 - $99 999,6,67,38
5d42a9f671d697001af667fc,Male,2,NaN,27,Bachelor's degree (3+),4,$10 000 - $19 999,2,50,50
613a639002c088d7e68b80a9,Male,2,NaN,27,Master's degree (5+),5,$10 000 - $19 999,2,17,51
5ed91f1e9c985546085a116f,Male,2,NaN,21,Bachelor's degree (3+),4,$10 000 - $19 999,2,19,0
6131cf33d4b5c450b104ca9e,Female,1,NaN,20,Bachelor's degree (3+),4,Less that $10 000,1,24,58
6141bdf9ebdc730adcc8d332,Male,2,NaN,21,High school graduate,2,Less that $10 000,1,50,99
5ebc6f18c323480b94409c78,Male,2,NaN,28,Bachelor's degree (3+),4,$10 000 - $19 999,2,31,0
613eba54614a8826b829b734,Female,1,NaN,20,Bachelor's degree (3+),4,Less that $10 000,1,40,62
601f3d6a08d6ec47b04ca28a,Male,2,NaN,21,Bachelor's degree (3+),4,Less that $10 000,1,42,14
611ae4c41ac95c70c7d2e67b,Male,2,NaN,35,Master's degree (5+),5,$20 000 - $29 999,3,29,6
5c38642b1ede2b0001156a1b,Female,1,NaN,42,High school graduate,2,$20 000 - $29 999,3,49,50
6163f0438cdf8e3d44667f2f,Female,1,NaN,20,Some college but no degree,3,$20 000 - $29 999,3,11,5
60f56f0103876eae7c0d870f,Female,1,NaN,18,High school graduate,2,Less that $10 000,1,55,91
6166ef334de9e433e83bfb79,Female,1,NaN,19,High school graduate,2,$50 000 - $69 999,5,60,100
60143a1a222eb43daf203877,Male,2,NaN,25,Bachelor's degree (3+),4,Less that $10 000,1,0,7
615ddcbe6b2ef828956206f5,Male,2,NaN,30,High school graduate,2,$20 000 - $29 999,3,49,56
5fb4f660e7d1522e042020df,Male,2,NaN,25,High school graduate,2,Less that $10 000,1,75,70
60ff113dd2eee15e8f4dfeee,Female,1,NaN,24,Bachelor's degree (3+),4,$100 000 - $149 999,7,19,30
613d398018d33fdb9701ed19,Male,2,NaN,21,Bachelor's degree (3+),4,Less that $10 000,1,16,27
5ddedc1ac5faa2e4d356d45d,Male,2,NaN,23,Master's degree (5+),5,$10 000 - $19 999,2,35,43
6107a72fb967e5834664701f,Female,1,NaN,26,Bachelor's degree (3+),4,$100 000 - $149 999,7,20,8
5999ad2a0ed7ae0001991b57,Male,2,NaN,29,Bachelor's degree (3+),4,$20 000 - $29 999,3,34,28
613e0db08ed0a1b88e057a44,Male,2,NaN,36,Bachelor's degree (3+),4,$70 000 - $99 999,6,28,50
5f20df2af5d0c24208c88315,Male,2,NaN,23,Bachelor's degree (3+),4,$50 000 - $69 999,5,16,8
5e95b5ae0295ea01d7ce532b,Female,1,NaN,48,High school graduate,2,$10 000 - $19 999,2,56,64
5e307a080551ae02939239f3,Female,1,NaN,23,Bachelor's degree (3+),4,$10 000 - $19 999,2,70,100
60339afe243dc403d0e2eab1,Female,1,NaN,22,High school graduate,2,Less that $10 000,1,10,14
60e1c5e1e506ceb7e0d46bae,Female,1,NaN,21,Some college but no degree,3,More than $150 000,8,16,38
6155dbebf281b0d024a1547e,Male,2,NaN,22,Bachelor's degree (3+),4,$10 000 - $19 999,2,10,12
60fca702ccf4e75d6baf1fc2,Female,1,NaN,20,Some college but no degree,3,$100 000 - $149 999,7,5,18
6106fd38393f15b301d745d2,Female,1,NaN,26,Master's degree (5+),5,NaN,NaN,10,0
5e5b08677394743009ffcc8b,Female,1,NaN,32,Master's degree (5+),5,$30 000 - $49 999,4,62,50
6090397fdf27ef27909b759c,Male,2,NaN,58,Master's degree (5+),5,$30 000 - $49 999,4,33,0
609d83db80dca3574b10fc71,Male,2,NaN,43,Bachelor's degree (3+),4,$20 000 - $29 999,3,66,64
5ea352855d02232c906f62d8,Female,1,NaN,21,Some college but no degree,3,$70 000 - $99 999,6,70,61
611d90d349308db31d30014f,Male,2,NaN,21,Bachelor's degree (3+),4,$10 000 - $19 999,2,15,66
5fe7b6d7baa7c46725b4e530,Male,2,NaN,21,Bachelor's degree (3+),4,$100 000 - $149 999,7,24,15
6063211b7de1f848fb436f5c,Female,1,NaN,24,Bachelor's degree (3+),4,$10 000 - $19 999,2,17,0
6106ce151a47f7b687062eea,Female,1,NaN,20,High school graduate,2,$20 000 - $29 999,3,14,9
5eaf0e378f26940719d2b02e,Male,2,NaN,31,Master's degree (5+),5,$10 000 - $19 999,2,39,57
6143273ed573af378dd0a0cb,Female,1,NaN,41,High school graduate,2,NaN,NaN,51,0
60399236302d0732bdb88541,Female,1,NaN,21,High school graduate,2,$70 000 - $99 999,6,57,52
614d9ea7c87980229c834d21,Male,2,NaN,20,High school graduate,2,$10 000 - $19 999,2,61,85
607de1d480f76e94ffb6e0ab,Female,1,NaN,19,High school graduate,2,$30 000 - $49 999,4,34,50
5d20e2135278fa00014814c0,Female,1,NaN,42,Master's degree (5+),5,$50 000 - $69 999,5,40,78
60fb0cd3aa10c5ef5100190b,Female,1,NaN,22,Bachelor's degree (3+),4,$10 000 - $19 999,2,20,0
611e3c4f4eae320e94284ea7,Female,1,NaN,29,Bachelor's degree (3+),4,Less that $10 000,1,30,97

In [62]:
# TASK LOGIC

# Collect participant ID
part_ids = task_raw[part_id_key].dropna().unique()

# Columns with relevant data

## Find variable names (could replace)
zone_key = 'Zone Name'
rating_val = 'agencyjudgement'
sense_val = 'sense' 
math_val = 'mathresponse1'
## Secondary keys
zone_sec_key = 'Zone Type'
rating_last_val = 'response_slider_endValue'
sense_sec_val = 'response_rating_scale_likert'
math_sec_val = 'response_text_entry'

## Find response column
response_key = 'Response'
## Reaction time
reaction_time_key = 'Reaction Time'

## Find words
word_left_key = 'word1'
word_right_key = 'word2'

# Math question col
math_question_key = 'math_question'

# Columns of interest
gen_keys = [zone_key, zone_sec_key, response_key, reaction_time_key]
task_math_keys = [math_question_key]
task_comparison_keys = [word_left_key, word_right_key]

# Formatting adjustments
def remove_article(my_string, filler='_'):
    split_string = my_string.split(' ')
    if len(split_string) > 1:
        return filler.join(split_string[1:])
    else:
        return my_string

In [186]:
agency_datasets = []
checks_columns = ['total_time_min', 'rock_human_score', 'rock_god_score', 'math1_num_resp', 'math2_num_resp', 'math3_num_resp']
df_checks = pd.DataFrame(columns=checks_columns)

for part_id in part_ids:
    #print(part_id)
    task_part = task_raw[task_raw[part_id_key] == part_id]

    # Get full elapsed time in milliseconds
    time_ml = int(task_part['Reaction Time'].dropna().tail(1))
    time_min = time_ml / 1000 / 60
    
    
    task_clean = task_part.drop(task_part.tail(1).index, axis=0)[gen_keys + task_math_keys + task_comparison_keys].rename({reaction_time_key:'reaction_time'}, axis=1)
    
    # Sense data
    sense_data_raw = task_clean[task_clean[zone_key] == sense_val].copy()
    series = (sense_data_raw[response_key] != 'Does not make sense').astype(int)
    sense_data_raw['sense_response'] = series
    sense_data = sense_data_raw.drop(task_math_keys + [zone_key, zone_sec_key, response_key], axis=1).reset_index(drop=True)

    # Agency data
    agency_data_raw_1 = task_clean[task_clean[zone_key] == rating_val]
    agency_data_raw = agency_data_raw_1[agency_data_raw_1[zone_sec_key] == rating_last_val].copy()
    agency_data_raw[response_key] = agency_data_raw[response_key].astype(int)
    agency_data_raw['left_score'] = agency_data_raw[response_key].apply(lambda x: 3 - x if x < 3 else 2 - x)
    agency_data_raw['right_score'] = agency_data_raw['left_score'].apply(lambda x: -x)
    agency_data_raw['left_score_binary'] = agency_data_raw['left_score'].apply(lambda x: 1 if x > 0 else 0)
    agency_data_raw['right_score_binary'] = agency_data_raw['right_score'].apply(lambda x: 1 if x > 0 else 0)
    #agency_data_raw['right_score'] = agency_data_raw[response_key].apply(lambda x: x - 2 if x > 2 else x - 3)
    agency_data = agency_data_raw.drop(task_math_keys + [zone_key, zone_sec_key, response_key], axis=1).reset_index(drop=True)
    
    # Group all data (sense and agency)
    task_data = agency_data.merge(sense_data, how='left')
    
    # Apply article removal
    task_data['word1'] = task_data['word1'].apply(remove_article)
    task_data['word2'] = task_data['word2'].apply(remove_article)
    # Rename words columns to left and right
    task_data = task_data.rename({'word1':'words_left', 'word2':'words_right'}, axis=1)

    # Store data
    agency_datasets.append(task_data)


    ## Checking dataframe
    # Checks dataframe
    ## Math data
    math_data_raw = task_clean[task_clean[zone_key] == math_val].copy()
    math_questions = [
        '9 + 7 + 9 =',
        '3 + 14 =',
        '9 / 3 ='
    ]
    math_attemps = np.zeros(len(math_questions))

    for i, q in enumerate(math_questions):
        math_attemps[i] = len(math_data_raw[math_data_raw[math_question_key] == q])

    # Task completion time
    explanation_time = task_raw[task_raw[zone_key] == 'advancementZone'][reaction_time_key].sum()
    fixation_time = task_raw[task_raw[zone_key] == 'fixation'][reaction_time_key].sum()
    transition_time = task_raw[task_raw[zone_sec_key] == 'timelimit_screen'][reaction_time_key].sum()

    full_time_manual = math_data_raw.reaction_time.sum() + task_data.reaction_time.sum() + explanation_time + fixation_time + transition_time

    rock_score = task_data[task_data.words_right == 'rock']
    rock_human_score = rock_score[rock_score.words_left == 'human'].reset_index(drop=True).loc[0, 'right_score']

    rock_score = task_data[task_data.words_right == 'rock']
    rock_god_score = rock_score[rock_score.words_left == 'god'].reset_index(drop=True).loc[0, 'right_score']

    # Aggregate data
    data = [time_min, rock_human_score, rock_god_score, math_attemps[0], math_attemps[1], math_attemps[2]]

    # Add data to dataframe
    df_checks.loc[part_id] = data

    df_checks
    
len(agency_datasets)

52

In [188]:
df_checks.reset_index()

,index,total_time_min,rock_human_score,rock_god_score,math1_num_resp,math2_num_resp,math3_num_resp
0,5e8f4d8918ca6c2314765d92,7.985300,-3.0,-3.0,3.0,1.0,1.0
1,614b53c4e3ff9739cc026895,4.849533,-3.0,-1.0,1.0,1.0,1.0
2,61133b44c0f877a21f27c3ee,11.283350,-3.0,-3.0,1.0,1.0,1.0
3,61088dc29d639b015d4cd918,4.899517,-3.0,-3.0,1.0,1.0,1.0
4,6175b756491e339b289ca959,5.419700,-3.0,1.0,1.0,1.0,1.0
5,60ad33772c5d282d6a2021e8,9.734767,-2.0,-2.0,1.0,1.0,3.0
6,5d42a9f671d697001af667fc,9.101067,-2.0,2.0,1.0,1.0,1.0
7,613a639002c088d7e68b80a9,8.077550,-3.0,-2.0,1.0,1.0,1.0
8,5ed91f1e9c985546085a116f,8.059567,-3.0,-3.0,1.0,1.0,1.0
9,6131cf33d4b5c450b104ca9e,7.558200,-2.0,2.0,1.0,1.0,1.0
10,6141bdf9ebdc730adcc8d332,13.864517,-3.0,-3.0,1.0,1.0,1.0
11,5ebc6f18c323480b94409c78,16.483467,-2.0,-3.0,1.0,1.0,1.0
12,613eba54614a8826b829b734,233.788617,-3.0,-1.0,1.0,1.0,1.0
13,601f3d6a08d6ec47b04ca28a,5.086667,-2.0,-1.0,1.0,1.0,1.0
14,611ae4c41ac95c70c7d2e67b,6.564250,-3.0,1.0,1.0,1.0,1.0
15,5c38642b1ede2b0001156a1b,33.910867,-3.0,1.0,1.0,1.0,1.0
16,6163f0438cdf8e3d44667f2f,8.598833,-2.0,1.0,1.0,1.0,1.0
17,60f56f0103876eae7c0d870f,11.279533,-3.0,-3.0,1.0,1.0,1.0
18,6166ef334de9e433e83bfb79,8.863567,-3.0,-3.0,1.0,1.0,1.0
19,60143a1a222eb43daf203877,7.417950,-3.0,-3.0,1.0,1.0,1.0
20,615ddcbe6b2ef828956206f5,4.601600,1.0,1.0,1.0,1.0,1.0
21,5fb4f660e7d1522e042020df,6.337767,-3.0,-3.0,1.0,1.0,1.0
22,60ff113dd2eee15e8f4dfeee,7.592833,-3.0,-3.0,1.0,1.0,1.0
23,613d398018d33fdb9701ed19,4.100683,-2.0,-2.0,1.0,1.0,1.0
24,5ddedc1ac5faa2e4d356d45d,4.100717,-3.0,-3.0,1.0,1.0,1.0
25,6107a72fb967e5834664701f,5.303533,-2.0,-3.0,1.0,1.0,1.0
26,5999ad2a0ed7ae0001991b57,2.837000,-2.0,-1.0,1.0,1.0,1.0
27,613e0db08ed0a1b88e057a44,3.393683,-2.0,-1.0,1.0,1.0,1.0
28,5f20df2af5d0c24208c88315,4.578167,-3.0,-3.0,1.0,1.0,1.0
29,5e95b5ae0295ea01d7ce532b,6.696383,-2.0,-1.0,1.0,1.0,1.0
30,5e307a080551ae02939239f3,4.628267,-3.0,-3.0,1.0,1.0,1.0
31,60339afe243dc403d0e2eab1,11.161700,-3.0,-3.0,1.0,1.0,1.0
32,60e1c5e1e506ceb7e0d46bae,6.402250,-3.0,-3.0,1.0,1.0,1.0
33,6155dbebf281b0d024a1547e,11.490200,-3.0,-3.0,3.0,1.0,1.0
34,60fca702ccf4e75d6baf1fc2,5.465650,-3.0,-2.0,1.0,1.0,1.0
35,6106fd38393f15b301d745d2,6.651900,-3.0,3.0,1.0,1.0,1.0
36,5e5b08677394743009ffcc8b,15.268950,-2.0,-1.0,1.0,1.0,1.0
37,6090397fdf27ef27909b759c,9.650367,-3.0,-3.0,1.0,1.0,1.0
38,609d83db80dca3574b10fc71,8.575817,-2.0,-1.0,1.0,1.0,1.0
39,5ea352855d02232c906f62d8,11.898800,-2.0,-1.0,1.0,1.0,1.0
40,611d90d349308db31d30014f,7.268683,-3.0,-3.0,1.0,1.0,1.0
41,5fe7b6d7baa7c46725b4e530,7.895517,-3.0,1.0,1.0,1.0,1.0
42,6063211b7de1f848fb436f5c,10.685467,-3.0,1.0,1.0,1.0,1.0
43,6106ce151a47f7b687062eea,6.065350,-3.0,-2.0,1.0,1.0,1.0
44,5eaf0e378f26940719d2b02e,5.517533,-2.0,-1.0,1.0,1.0,1.0
45,6143273ed573af378dd0a0cb,9.605183,-3.0,3.0,1.0,1.0,1.0
46,60399236302d0732bdb88541,9.277133,-3.0,-3.0,1.0,1.0,1.0
47,614d9ea7c87980229c834d21,8.436400,-3.0,-1.0,1.0,1.0,1.0
48,607de1d480f76e94ffb6e0ab,5.478950,-3.0,-3.0,1.0,1.0,1.0
49,5d20e2135278fa00014814c0,13.335050,-3.0,-3.0,1.0,1.0,1.0
50,60fb0cd3aa10c5ef5100190b,7.686217,-3.0,-3.0,1.0,1.0,1.0
51,611e3c4f4eae320e94284ea7,12.020467,-3.0,3.0,1.0,1.0,1.0

In [178]:
# Create matrices and array
## Score, binary, sense
words = pd.Series(list(task_data.words_left) + list(task_data.words_right)).unique()

aggregate_columns = ['mean_score', 'score_std', 'win_prob', 'win_prob_std', 'sense_prob', 'sense_std']

score_matrix = np.zeros((len(part_ids), len(words), len(words)))
win_matrix = np.zeros((len(part_ids), len(words), len(words)))
sense_matrix = np.zeros((len(part_ids), len(words), len(words)))
aggregate_matrix = np.zeros((len(part_ids), len(words), len(aggregate_columns)))

dfs_scores = []
dfs_wins = []
dfs_sense = []
dfs_aggregate = []

for k, part_id in enumerate(part_ids):
    
    matrix_prep = agency_datasets[k].copy()

    for word in words:
        matrix_prep[word + '_left'] = (matrix_prep.words_left == word).astype(int)
        matrix_prep[word + '_right'] = (matrix_prep.words_right == word).astype(int)
        matrix_prep[word + '_in'] = matrix_prep[word + '_left'] + matrix_prep[word + '_right']

        #matrix_prep[word + '_score'] = matrix_prep.apply(lambda x: x['left_score'] if x['words_left'] == word else x['right_score'])

        matrix_prep.loc[matrix_prep.words_left == word, word + '_score'] = matrix_prep.left_score
        matrix_prep.loc[matrix_prep.words_right == word, word + '_score'] = matrix_prep.right_score

        matrix_prep.loc[matrix_prep.words_left == word, word + '_score_binary'] = matrix_prep.left_score_binary
        matrix_prep.loc[matrix_prep.words_right == word, word + '_score_binary'] = matrix_prep.right_score_binary
        matrix_prep.drop([word + '_left', word + '_right'], axis=1, inplace=True)


    pairwise_scores = pd.DataFrame()
    pairwise_binaries = pd.DataFrame()
    sense_mat = pd.DataFrame()

    for i, word1 in enumerate(words):
        scores_1 = matrix_prep[matrix_prep[word1 + '_in'] == 1]
        for j, word2 in enumerate(words):
            if word1 == word2:
                pairwise_scores.loc[word2, word1] = np.nan
                pairwise_binaries.loc[word2, word1] = np.nan
                sense_mat.loc[word2, word1] = np.nan
                continue
            #print(len(scores_1[scores_1.words_left == word2]))
            if len(scores_1[scores_1.words_left == word2]):
                scores_2 = scores_1[scores_1.words_left == word2].reset_index()
            else:
                scores_2 = scores_1[scores_1.words_right == word2].reset_index()

            pairwise_scores.loc[word2, word1] = scores_2.loc[0, word1 + '_score']
            pairwise_binaries.loc[word2, word1] = scores_2.loc[0, word1 + '_score_binary']
            sense_mat.loc[word2, word1] = scores_2.loc[0, 'sense_response']
 
    # In matrices, columns are the pespective of words while row is the perspective of opponents

    # Create aggregate dataframe to be averaged over participants
    df_aggregate = pd.DataFrame()

    df_aggregate[aggregate_columns[0]] = pairwise_scores.mean()
    df_aggregate[aggregate_columns[1]] = pairwise_scores.std()
    df_aggregate[aggregate_columns[2]] = pairwise_binaries.mean()
    df_aggregate[aggregate_columns[3]] = pairwise_binaries.std()
    df_aggregate[aggregate_columns[4]] = sense_mat.mean()
    df_aggregate[aggregate_columns[5]] = sense_mat.std()

    # Store data in arrays
    score_matrix[k, :, :] = pairwise_scores.to_numpy()
    win_matrix[k, :, :] = pairwise_binaries.to_numpy()
    sense_matrix[k, :, :] = sense_mat.to_numpy()
    aggregate_matrix[k, :, :] = df_aggregate.to_numpy()


    dfs_scores.append(pairwise_scores)
    dfs_wins.append(pairwise_binaries)
    dfs_sense.append(sense_mat)
    dfs_aggregate.append(df_aggregate)

    #print(sense_matrix)
    #if k > 2:
    #    break

In [219]:
# AGGREGATE DATASETS (averaged over participants)
# Generate global datasets
df_score = pd.DataFrame(index=pairwise_binaries.index, columns=pairwise_binaries.columns, data=score_matrix.mean(axis=0))
df_win = pd.DataFrame(index=pairwise_binaries.index, columns=pairwise_binaries.columns, data=win_matrix.mean(axis=0))
df_sense = pd.DataFrame(index=pairwise_binaries.index, columns=pairwise_binaries.columns, data=sense_matrix.mean(axis=0))

final_aggregate = pd.DataFrame(index=pairwise_scores.index, columns=df_aggregate.columns, data=aggregate_matrix.mean(axis=0))#.sort_values('mean_score', ascending=False)

# Save files
df_checks.to_excel('.\\data\\datasets_excel\\sanity_checks.xlsx')
df_demos.to_excel('.\\data\\datasets_excel\\demographics.xlsx')
df_score.to_excel('.\\data\\datasets_excel\\scores.xlsx')
df_win.to_excel('.\\data\\datasets_excel\\probability_win.xlsx')
df_sense.to_excel('.\\data\\datasets_excel\\sense.xlsx')
final_aggregate.to_excel('.\\data\\datasets_excel\\summaries.xlsx')

df_checks.to_csv('.\\data\\datasets\\sanity_checks.csv')
df_demos.to_csv('.\\data\\datasets\\demographics.csv')
df_score.to_csv('.\\data\\datasets\\scores.csv')
df_win.to_csv('.\\data\\datasets\\probability_win.csv')
df_sense.to_csv('.\\data\\datasets\\sense.csv')
final_aggregate.to_csv('.\\data\\datasets\\summaries.csv')

In [224]:
# PARTICIPANT-WISE DATASETS
index_2d = pd.MultiIndex.from_product([part_ids, words], names=['part_id', 'word'])

score_dataset = score_matrix.reshape((len(part_ids) * len(words), len(words)))
win_dataset = win_matrix.reshape((len(part_ids) * len(words), len(words)))
sense_dataset = sense_matrix.reshape((len(part_ids) * len(words), len(words)))
aggregate_dataset = aggregate_matrix.reshape((len(part_ids) * len(words), len(aggregate_columns)))

df_score_full = pd.DataFrame(data=score_dataset, index=index_2d, columns=df_score.columns)
df_win_full = pd.DataFrame(data=win_dataset, index=index_2d, columns=df_score.columns)
df_sense_full = pd.DataFrame(data=sense_dataset, index=index_2d, columns=df_score.columns)
df_aggregate_full = pd.DataFrame(data=aggregate_dataset, index=index_2d, columns=aggregate_columns)


df_score_full.to_excel('.\\data\\datasets_excel\\scores_participants.xlsx')
df_win_full.to_excel('.\\data\\datasets_excel\\probability_win_participants.xlsx')
df_sense_full.to_excel('.\\data\\datasets_excel\\sense_participants.xlsx')
df_aggregate_full.to_excel('.\\data\\datasets_excel\\summaries_participants.xlsx')

df_score_full.to_csv('.\\data\\datasets\\scores_participants.csv')
df_win_full.to_csv('.\\data\\datasets\\probability_win_participants.csv')
df_sense_full.to_csv('.\\data\\datasets\\sense_participants.csv')
df_aggregate_full.to_csv('.\\data\\datasets\\summaries_participants.csv')

# Metadata for later processing
pd.Series(words).to_csv(".\\data\\datasets\\word_list.csv", header=False, index=False)
pd.Series(part_ids).to_csv(".\\data\\datasets\\participants_ids.csv", header=False, index=False)

In [221]:
# FULL TRIALS DATASET
trials_index = pd.MultiIndex.from_product([part_ids, task_data.index], names=['part_id', 'words'])

trials_dataset = pd.concat(agency_datasets).values

df_trials = pd.DataFrame(data=trials_dataset, index=trials_index, columns=task_data.columns)

df_trials.to_excel('.\\data\\datasets_excel\\trials_participants.xlsx')
df_trials.to_csv('.\\data\\datasets\\trials_participants.csv')

In [226]:
#test_recover = pd.read_csv('.\\data\\datasets\\trials_participants.csv')
#test_recover.set_index(['part_id', 'words'])

                                reaction_time               words_left  \
part_id                  words
5e8f4d8918ca6c2314765d92 0            21258.0                    robot
                         1             8154.0               jelly_fish
                         2             8700.0               chimpanzee
                         3             4746.0  artificial_intelligence
                         4             5518.0                    human
...                                       ...                      ...
611e3c4f4eae320e94284ea7 40            4257.0                    virus
                         41            7932.3                    robot
                         42            4567.9                    robot
                         43            4552.0                    human
                         44            4848.3                    human

                                            words_right  left_score  \
part_id                  words
5e8f4d8918ca6c2314765d92 0      artificial_intelligence          -2
                         1                          god          -3
                         2                          god          -2
                         3                     computer           2
                         4                         rock           3
...                                                 ...         ...
611e3c4f4eae320e94284ea7 40              autonomous_car          -3
                         41                        rock           3
                         42     artificial_intelligence          -3
                         43              autonomous_car          -3
                         44                        rock           3

                                right_score  left_score_binary  \
part_id                  words
5e8f4d8918ca6c2314765d92 0                2                  0
                         1                3                  0
                         2                2                  0
                         3               -2                  1
                         4               -3                  1
...                                     ...                ...
611e3c4f4eae320e94284ea7 40               3                  0
                         41              -3                  1
                         42               3                  0
                         43               3                  0
                         44              -3                  1

                                right_score_binary  sense_response
part_id                  words
5e8f4d8918ca6c2314765d92 0                       1               1
                         1                       1               1
                         2                       1               1
                         3                       0               1
                         4                       0               1
...                                            ...             ...
611e3c4f4eae320e94284ea7 40                      1               1
                         41                      0               1
                         42                      1               1
                         43                      1               1
                         44                      0               1

[2340 rows x 8 columns]

In [176]:
df_win

,chimpanzee,jelly_fish,autonomous_car,virus,human,robot,rock,artificial_intelligence,god,computer
chimpanzee,NaN,0.076923,0.538462,0.384615,0.903846,0.480769,0.115385,0.615385,0.634615,0.557692
jelly_fish,0.923077,NaN,0.653846,0.615385,1.000000,0.673077,0.192308,0.692308,0.769231,0.692308
autonomous_car,0.461538,0.346154,NaN,0.538462,0.846154,0.519231,0.057692,0.750000,0.576923,0.634615
virus,0.615385,0.384615,0.461538,NaN,0.826923,0.519231,0.057692,0.634615,0.673077,0.500000
human,0.096154,0.000000,0.153846,0.173077,NaN,0.153846,0.019231,0.173077,0.307692,0.192308
robot,0.519231,0.326923,0.480769,0.480769,0.846154,NaN,0.038462,0.730769,0.557692,0.500000
rock,0.884615,0.807692,0.942308,0.942308,0.980769,0.961538,NaN,0.961538,0.769231,0.980769
artificial_intelligence,0.384615,0.307692,0.250000,0.365385,0.826923,0.269231,0.038462,NaN,0.500000,0.269231
god,0.365385,0.230769,0.423077,0.326923,0.692308,0.442308,0.230769,0.500000,NaN,0.423077
computer,0.442308,0.307692,0.365385,0.500000,0.807692,0.500000,0.019231,0.730769,0.576923,NaN

In [177]:
df_sense

,chimpanzee,jelly_fish,autonomous_car,virus,human,robot,rock,artificial_intelligence,god,computer
chimpanzee,NaN,0.807692,0.807692,0.692308,0.961538,0.846154,0.730769,0.865385,0.750000,0.807692
jelly_fish,0.807692,NaN,0.673077,0.673077,0.788462,0.730769,0.673077,0.730769,0.673077,0.692308
autonomous_car,0.807692,0.673077,NaN,0.673077,0.826923,0.826923,0.730769,0.846154,0.711538,0.788462
virus,0.692308,0.673077,0.673077,NaN,0.865385,0.750000,0.673077,0.788462,0.750000,0.750000
human,0.961538,0.788462,0.826923,0.865385,NaN,0.961538,0.846154,0.942308,0.884615,0.884615
robot,0.846154,0.730769,0.826923,0.750000,0.961538,NaN,0.692308,0.807692,0.711538,0.846154
rock,0.730769,0.673077,0.730769,0.673077,0.846154,0.692308,NaN,0.807692,0.634615,0.730769
artificial_intelligence,0.865385,0.730769,0.846154,0.788462,0.942308,0.807692,0.807692,NaN,0.730769,0.865385
god,0.750000,0.673077,0.711538,0.750000,0.884615,0.711538,0.634615,0.730769,NaN,0.750000
computer,0.807692,0.692308,0.788462,0.750000,0.884615,0.846154,0.730769,0.865385,0.750000,NaN

In [189]:
final_aggregate.sort_values('mean_score', ascending=False)

,mean_score,score_std,win_prob,win_prob_std,sense_prob,sense_std
human,1.715812,1.304238,0.858974,0.244133,0.884615,0.141865
god,0.568376,1.275334,0.596154,0.288719,0.732906,0.230378
artificial_intelligence,0.549145,1.790014,0.643162,0.440092,0.820513,0.186641
computer,0.183761,1.876812,0.527778,0.458719,0.790598,0.238560
chimpanzee,0.051282,1.844647,0.521368,0.447215,0.807692,0.217473
robot,-0.029915,1.898125,0.502137,0.486843,0.797009,0.216953
virus,-0.121795,1.780110,0.480769,0.465756,0.735043,0.222524
autonomous_car,-0.168803,1.821024,0.474359,0.455323,0.764957,0.214883
jelly_fish,-0.871795,1.586080,0.309829,0.364910,0.715812,0.219638
rock,-1.876068,1.008637,0.085470,0.160575,0.724359,0.242488

In [190]:
df_sense.mean().sort_values(ascending=False)

human                      0.884615
artificial_intelligence    0.820513
chimpanzee                 0.807692
robot                      0.797009
computer                   0.790598
autonomous_car             0.764957
virus                      0.735043
god                        0.732906
rock                       0.724359
jelly_fish                 0.715812
dtype: float64

In [194]:
dfs_aggregate[20].sort_values('mean_score', ascending=False)

,mean_score,score_std,win_prob,win_prob_std,sense_prob,sense_std
artificial_intelligence,2.333333,0.500000,1.000000,0.000000,1.0,0.0
computer,1.666667,1.414214,0.888889,0.333333,1.0,0.0
robot,0.666667,2.291288,0.666667,0.500000,1.0,0.0
autonomous_car,0.111111,1.615893,0.666667,0.500000,1.0,0.0
virus,0.000000,2.000000,0.444444,0.527046,1.0,0.0
rock,-0.111111,1.615893,0.555556,0.527046,1.0,0.0
god,-0.222222,2.048034,0.444444,0.527046,1.0,0.0
human,-1.333333,1.500000,0.222222,0.440959,1.0,0.0
chimpanzee,-1.444444,1.509231,0.111111,0.333333,1.0,0.0
jelly_fish,-1.666667,0.707107,0.000000,0.000000,1.0,0.0

In [197]:
df_checks.sort_values('total_time_min')

,total_time_min,rock_human_score,rock_god_score,math1_num_resp,math2_num_resp,math3_num_resp
5999ad2a0ed7ae0001991b57,2.837000,-2.0,-1.0,1.0,1.0,1.0
613e0db08ed0a1b88e057a44,3.393683,-2.0,-1.0,1.0,1.0,1.0
613d398018d33fdb9701ed19,4.100683,-2.0,-2.0,1.0,1.0,1.0
5ddedc1ac5faa2e4d356d45d,4.100717,-3.0,-3.0,1.0,1.0,1.0
5f20df2af5d0c24208c88315,4.578167,-3.0,-3.0,1.0,1.0,1.0
615ddcbe6b2ef828956206f5,4.601600,1.0,1.0,1.0,1.0,1.0
5e307a080551ae02939239f3,4.628267,-3.0,-3.0,1.0,1.0,1.0
614b53c4e3ff9739cc026895,4.849533,-3.0,-1.0,1.0,1.0,1.0
61088dc29d639b015d4cd918,4.899517,-3.0,-3.0,1.0,1.0,1.0
601f3d6a08d6ec47b04ca28a,5.086667,-2.0,-1.0,1.0,1.0,1.0
6107a72fb967e5834664701f,5.303533,-2.0,-3.0,1.0,1.0,1.0
6175b756491e339b289ca959,5.419700,-3.0,1.0,1.0,1.0,1.0
60fca702ccf4e75d6baf1fc2,5.465650,-3.0,-2.0,1.0,1.0,1.0
607de1d480f76e94ffb6e0ab,5.478950,-3.0,-3.0,1.0,1.0,1.0
5eaf0e378f26940719d2b02e,5.517533,-2.0,-1.0,1.0,1.0,1.0
6106ce151a47f7b687062eea,6.065350,-3.0,-2.0,1.0,1.0,1.0
5fb4f660e7d1522e042020df,6.337767,-3.0,-3.0,1.0,1.0,1.0
60e1c5e1e506ceb7e0d46bae,6.402250,-3.0,-3.0,1.0,1.0,1.0
611ae4c41ac95c70c7d2e67b,6.564250,-3.0,1.0,1.0,1.0,1.0
6106fd38393f15b301d745d2,6.651900,-3.0,3.0,1.0,1.0,1.0
5e95b5ae0295ea01d7ce532b,6.696383,-2.0,-1.0,1.0,1.0,1.0
611d90d349308db31d30014f,7.268683,-3.0,-3.0,1.0,1.0,1.0
60143a1a222eb43daf203877,7.417950,-3.0,-3.0,1.0,1.0,1.0
6131cf33d4b5c450b104ca9e,7.558200,-2.0,2.0,1.0,1.0,1.0
60ff113dd2eee15e8f4dfeee,7.592833,-3.0,-3.0,1.0,1.0,1.0
60fb0cd3aa10c5ef5100190b,7.686217,-3.0,-3.0,1.0,1.0,1.0
5fe7b6d7baa7c46725b4e530,7.895517,-3.0,1.0,1.0,1.0,1.0
5e8f4d8918ca6c2314765d92,7.985300,-3.0,-3.0,3.0,1.0,1.0
5ed91f1e9c985546085a116f,8.059567,-3.0,-3.0,1.0,1.0,1.0
613a639002c088d7e68b80a9,8.077550,-3.0,-2.0,1.0,1.0,1.0
614d9ea7c87980229c834d21,8.436400,-3.0,-1.0,1.0,1.0,1.0
609d83db80dca3574b10fc71,8.575817,-2.0,-1.0,1.0,1.0,1.0
6163f0438cdf8e3d44667f2f,8.598833,-2.0,1.0,1.0,1.0,1.0
6166ef334de9e433e83bfb79,8.863567,-3.0,-3.0,1.0,1.0,1.0
5d42a9f671d697001af667fc,9.101067,-2.0,2.0,1.0,1.0,1.0
60399236302d0732bdb88541,9.277133,-3.0,-3.0,1.0,1.0,1.0
6143273ed573af378dd0a0cb,9.605183,-3.0,3.0,1.0,1.0,1.0
6090397fdf27ef27909b759c,9.650367,-3.0,-3.0,1.0,1.0,1.0
60ad33772c5d282d6a2021e8,9.734767,-2.0,-2.0,1.0,1.0,3.0
6063211b7de1f848fb436f5c,10.685467,-3.0,1.0,1.0,1.0,1.0
60339afe243dc403d0e2eab1,11.161700,-3.0,-3.0,1.0,1.0,1.0
60f56f0103876eae7c0d870f,11.279533,-3.0,-3.0,1.0,1.0,1.0
61133b44c0f877a21f27c3ee,11.283350,-3.0,-3.0,1.0,1.0,1.0
6155dbebf281b0d024a1547e,11.490200,-3.0,-3.0,3.0,1.0,1.0
5ea352855d02232c906f62d8,11.898800,-2.0,-1.0,1.0,1.0,1.0
611e3c4f4eae320e94284ea7,12.020467,-3.0,3.0,1.0,1.0,1.0
5d20e2135278fa00014814c0,13.335050,-3.0,-3.0,1.0,1.0,1.0
6141bdf9ebdc730adcc8d332,13.864517,-3.0,-3.0,1.0,1.0,1.0
5e5b08677394743009ffcc8b,15.268950,-2.0,-1.0,1.0,1.0,1.0
5ebc6f18c323480b94409c78,16.483467,-2.0,-3.0,1.0,1.0,1.0
5c38642b1ede2b0001156a1b,33.910867,-3.0,1.0,1.0,1.0,1.0
613eba54614a8826b829b734,233.788617,-3.0,-1.0,1.0,1.0,1.0